
# basic options
title: What's Up Walk
author: A. Nazamusa
email: aliahnaza@gmail.com
description: Testing github talent
twitter_username: walkingA
github_username: aliahnazamusa

# Build settings
markdown: kramdown
theme: minima
